Uncommented tests for githooks as everyone will have a key. Commented out tests in docker.

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -4,11 +4,11 @@ echo "Running pycodestyle for src/"
 pycodestyle --statistics -qq src
 echo "Running pycodestyle for tests/"
 pycodestyle --statistics -qq tests
-# python -m unittest 
-# if [ $? -ne 0 ]
-# then
-# 	echo "Unit tests failed"
-# 	exit 1
-# fi
+python -m unittest 
+if [ $? -ne 0 ]
+then
+	echo "Unit tests failed"
+	exit 1
+fi
 
 exit 0
